# Generated by Django 4.1.4 on 2023-02-08 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('aula', '0002_institucion_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='incidencia',
            fields=[
                ('idIncidencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.alumnos')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.aula')),
            ],
        ),
    ]
