# Generated by Django 4.1.4 on 2023-02-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('incidencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='alumno',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='alumno',
            field=models.ManyToManyField(null=True, to='alumnos.alumnos'),
        ),
    ]
