# Generated by Django 3.2.18 on 2023-02-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='licencias',
            fields=[
                ('key', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('activation_date', models.DateField(auto_now_add=True)),
                ('expired_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='planes',
            fields=[
                ('nombre_plan', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('precio', models.CharField(max_length=15)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('license', models.ManyToManyField(null=True, to='licencia.licencias')),
            ],
        ),
    ]
