# Generated by Django 3.2.18 on 2023-02-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencias',
            name='is_usado',
            field=models.BooleanField(default=False),
        ),
    ]
