# Generated by Django 3.2.18 on 2023-02-25 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licencia', '0003_licencias_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='license',
            field=models.ManyToManyField(default=django.db.models.deletion.SET_NULL, null=True, to='licencia.licencias'),
        ),
    ]
