# Generated by Django 3.2.18 on 2023-02-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencia', '0004_alter_planes_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='license',
            field=models.ManyToManyField(null=True, to='licencia.licencias'),
        ),
    ]
