# Generated by Django 4.1.4 on 2023-02-02 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='institucion',
            fields=[
                ('idInstitucion', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('PRI', 'Privado'), ('PUB', 'Publico')], max_length=3)),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='aula',
            fields=[
                ('idAula', models.BigAutoField(primary_key=True, serialize=False)),
                ('seccion', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=10)),
                ('nivel', models.CharField(choices=[('PRI', 'Primaria'), ('SEC', 'Secundaria'), ('SUP', 'Superior'), ('AFI', 'Afiansiamiento'), ('OTR', 'Otro')], max_length=3)),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3)),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula.institucion')),
            ],
        ),
    ]
