# Generated by Django 4.1.4 on 2023-02-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='periodo.periodo'),
        ),
    ]
