# Generated by Django 3.2.18 on 2023-02-23 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('license', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='licencia.licencias')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
