# Generated by Django 4.1.4 on 2023-02-12 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notas',
            fields=[
                ('idNota', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumnos')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.area')),
            ],
        ),
    ]
