# Generated by Django 4.1.4 on 2023-02-02 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='horario',
            fields=[
                ('idHorario', models.BigAutoField(primary_key=True, serialize=False)),
                ('turno', models.CharField(choices=[('MAN', 'Mañana'), ('TAR', 'Tarde'), ('NOC', 'Noche')], max_length=3)),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miercoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sabado'), ('DOM', 'Domingo')], max_length=3)),
                ('horainicio', models.TimeField()),
                ('horafin', models.TimeField()),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3)),
                ('areas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.area')),
                ('aulas', models.ManyToManyField(blank=True, null=True, to='aula.aula')),
            ],
        ),
    ]
