# Generated by Django 4.1.4 on 2023-02-18 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_institucion_periodo'),
        ('area', '0001_initial'),
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='areas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.area'),
        ),
        migrations.RemoveField(
            model_name='horario',
            name='aulas',
        ),
        migrations.AddField(
            model_name='horario',
            name='aulas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aula.aula'),
        ),
    ]
