# Generated by Django 3.2.18 on 2023-02-25 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horario', '0002_alter_horario_areas_remove_horario_aulas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
